#ifndef _SOSCL_TESTING_CONFIG_H
#define _SOSCL_TESTING_CONFIG_H

#define SOSCL_TEST_HASH
#define SOSCL_TEST_ECDSA
#define SOSCL_TEST_HMAC
#define SOSCL_TEST_SECP384R1
#define SOSCL_TEST_SECP256R1
#define SOSCL_TEST_SECP521R1
#define SOSCL_TEST_HASH_SHA384
#define SOSCL_TEST_HASH_SHA256
#define SOSCL_TEST_HASH_SHA512
#define SOSCL_TEST_ECC

int soscl_testing(void);
#endif//SOSCL_TESTING_CONFIG_H
